# Generated by Django 3.1.1 on 2020-09-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listapp',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
